title = "SHeM Ray Tracing Library Example Configuration"
description = "An example configuration file which showcases the capabilities of the library. See comments for more information."
npixels = 128
# How many rays to be traced in parallel for each pixel. Lower this if Python screams about memory requirements.
nparallel = 2
# How many segments to split the simulation into on the GPU. Raise this if Python screams about memory requirements.
blocks = 32
# How many times to repeat the same ray-tracing simulation
passes = 2

[scattering]
n = 5

[scattering.specular]
strength = 80
[scattering.diffuse]
strength = 20

[scan]
x_axis = 'x'
y_axis = 'y'
x_shift = 0.00
y_shift = 0.00
z_shift = 0.00

[scan.x]
range = 0.8
[scan.y]
range = 0.8
[scan.theta]
range = 0.0
[scan.phi]
range = 0.0

# Information lost due to thermal expansion. Cyclinder -> Cone
# Adiabatic expansion - calculate analytically.
# Angle is negligibly small.
# Lost information about incoming wavevector.
# Justify point source physically
[source]
radius = 0.1
location = [-1.0, 0.0, 1.0]

[source.function.delta]
strength = 10
[source.function.uniform_cone]
strength = 90
delta_theta = 0.1
delta_phi = 0.1


# Can define multiple detectors
[detector]

[detector.one]
radius = 0.05
location = [1.00, 0.00, 1.00]

